# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"UNDevice": "00_core.ipynb",
         "PPDevice": "00_core.ipynb",
         "PPController": "00_core.ipynb",
         "ID_CODE": "01_codes.ipynb",
         "REG_CODE": "01_codes.ipynb",
         "REG_VAL_LEN": "01_codes.ipynb",
         "CMD_CATALOG": "01_codes.ipynb",
         "CMD_CODE": "01_codes.ipynb",
         "CMD_NAME": "01_codes.ipynb",
         "CMD_VAL_LEN": "01_codes.ipynb",
         "ReportData": "20_reports.ipynb",
         "stats_struct": "20_reports.ipynb"}

modules = ["core.py",
           "codes.py",
           "schedule.py",
           "reports.py"]

doc_url = "https://durapensa.github.io/CircuitPython_pico_pi_controller/"

git_url = "https://github.com/durapensa/CircuitPython_pico_pi_controller/tree/main/"

def custom_doc_links(name): return None
