# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"UNDevice": "00_core.ipynb",
         "PPDevice": "00_core.ipynb",
         "PPController": "00_core.ipynb",
         "ReportData": "20_reports.ipynb",
         "stats_struct": "20_reports.ipynb"}

modules = ["core.py",
           "schedule.py",
           "reports.py"]

doc_url = "https://durapensa.github.io/CircuitPython_pico_pi_controller/"

git_url = "https://github.com/durapensa/CircuitPython_pico_pi_controller/tree/main/"

def custom_doc_links(name): return None
