# AUTOGENERATED! DO NOT EDIT! File to edit: 30_persist.ipynb (unless otherwise specified).

__all__ = ['show_free', 'wrt_ppds']

# Cell

#import json
#from CircuitPython_pico_pi_common.codes import *
import gc
import json
#import CircuitPython_pico_pi_controller.reports as PPR
from .reports import ReportData

# Cell

# imported as PPController.persist, methods should be interpreted as instance methods.
# json module impported as PPController.json

@staticmethod
def show_free(logger,id_str,i2c_str):
    fname='show_free'
    logger.info('%-6s %-27s %-9s %s' % (id_str, gc.mem_free() , fname, i2c_str))

@staticmethod
def wrt_ppds(serial_ppds):
    """Saves PPDevice values to flash storage. Optional."""
    fname='wrt_ppds'
    with open("/PPC.txt", "a") as ppd_file:
        json.dump(serial_ppds, ppd_file, indent = 8)
    ppd_file.close()
